# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.1.29

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - apt-get update && apt-get install -y unzip
          - apt-get update
          - add-apt-repository ppa:ondrej/php
          - apt-get update
          - apt-get install php7.2
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - rm -rf composer.lock
          - composer install
          - cp .env.example .env
          - php artisan key:generate
          - php artisan cache:clear
          - php artisan config:clear
          - php artisan config:cache
          - vendor/bin/phpunit

